name: heart_disease_mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.2.1
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - joblib=1.3.2
  - click=8.1.7
  - conda-forge::mlflow>=2.8.0
  - pip:
    - dagshub>=0.3.0
    - plotly>=5.15.0
    - kaleido>=0.2.1