name: heart-disease-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow>=2.8.0
    - pandas>=1.5.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - matplotlib>=3.6.0
    - seaborn>=0.12.0
    - joblib>=1.3.0
    - click>=8.0.0
    - boto3>=1.26.0
    - docker>=6.0.0